"""
fsw_sil_test.py
---------------
Software-In-the-Loop (SIL) Integration Test.
Runs the new Onboard Autonomy Agent flight software against the simulated 
MultiSatelliteEnv physics backend, demonstrating the AI sandbox and FDIR.
"""

import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from fsw.main import OnboardAutonomyAgent
from fsw.hal.sim_backend import SimEPS, SimThermal, SimADCS, SimRadio, SimFaultMonitor
from simulation.satellite_env import MultiSatelliteEnv
from simulation.sat_config import PRESETS
import logging

logging.getLogger().setLevel(logging.INFO)

def run_sil_test():
    # 1. Setup Simulation Environment
    config = PRESETS["starlink_leo"]
    sim_env = MultiSatelliteEnv(config=config, max_steps=100)
    
    # Force some initial faults for testing FDIR
    sim_env.curriculum_phase = 6
    obs_list, _ = sim_env.reset()
    
    # We will instantiate the FSW for Satellite 0 only for this test
    agent_idx = 0
    
    # 2. Setup Hardware Abstraction Layer (connected to sim)
    hal_eps = SimEPS(sim_env, agent_idx)
    hal_thermal = SimThermal(sim_env, agent_idx)
    hal_adcs = SimADCS(sim_env, agent_idx)
    hal_radio = SimRadio(sim_env, agent_idx)
    hal_fault = SimFaultMonitor(sim_env, agent_idx)
    
    # 3. Instantiate Flight Software
    fsw = OnboardAutonomyAgent(
        hal_eps, hal_thermal, hal_adcs, hal_radio, hal_fault,
        sim_env_ref=sim_env, agent_idx=agent_idx
    )
    
    # 4. Run SIL Loop
    logging.info("Starting FSW SIL Integration Test...")
    
    for tick in range(20):
        logging.info(f"--- TICK {tick} ---")
        # Run FSW scheduler for 1 tick (10 Hz nominal, here we just do 1 loop iteration)
        # Note: the scheduler is designed for real-time. For SIL step-by-step, we manually 
        # call the tasks to maintain sync with the physics step.
        fsw.task_read_telemetry()
        fsw.task_fdir()
        fsw.task_gnc_ai()
        
        # Pull the command generated by the FSW out of the HAL
        cmd = hal_adcs.last_command
        logging.info(f"FSW Actuator Command: {cmd}")
        
        # Step the actual physics environment
        # We pass zero-actions for all other satellites for this single-agent test
        actions = [[0.0] * 8 for _ in range(config.num_satellites)]
        actions[agent_idx] = cmd
        sim_env.step(actions)
        
    logging.info("SIL Integration Test Complete.")

if __name__ == "__main__":
    run_sil_test()
