"""
aws/aws_train_entry.py
======================
SageMaker entry-point for RL (Reinforcement Learning) training.

This is NOT supervised learning — there is NO dataset.
The agent learns entirely by interacting with the satellite simulation.

What this script does:
1. Installs RL dependencies (stable-baselines3, gymnasium)
2. Optionally restores pre-trained brain weights (for continual learning)
3. Calls mappo_train.main() — which runs the RL simulation loop
4. Saves the trained brain weights to S3

DO NOT EDIT this file unless you need custom container setup.
"""

import os
import sys
import subprocess
import shutil
import glob
import zipfile

# ── SageMaker standard paths ───────────────────────────────────────────────
SM_MODEL  = "/opt/ml/model"        # output: SageMaker uploads this to S3
SM_CKPT   = "/opt/ml/checkpoints"  # spot resume: persisted between interruptions
SM_WEIGHTS = "/opt/ml/input/data/weights"  # optional: pre-trained brain input

# SageMaker puts our source_dir here:
CODE_DIR = os.path.dirname(os.path.abspath(__file__))  # project root

os.makedirs(SM_MODEL, exist_ok=True)
os.makedirs(SM_CKPT,  exist_ok=True)
os.chdir(CODE_DIR)
sys.path.insert(0, CODE_DIR)

print("=" * 60)
print("  SATELLITE SWARM RL TRAINING — AWS SageMaker")
print("  Mode: Reinforcement Learning (no dataset needed)")
print(f"  Working dir: {CODE_DIR}")
print("=" * 60)

# ── 1. Install RL dependencies ─────────────────────────────────────────────
print("\n[1/4] Installing dependencies...")
subprocess.run([
    sys.executable, "-m", "pip", "install", "-q",
    "stable-baselines3>=2.3.0,<3.0",
    "gymnasium>=0.29,<1.1",
    "astropy",
], check=True)
print("  Done.")

# ── 2. Restore brain weights (for continual learning / warm start) ─────────
print("\n[2/4] Checking for pre-trained weights (continual learning)...")

MODEL_FILE = "ppo_swarm_brain.zip"
EWC_FILE   = "ewc_fisher_swarm.pkl"

# Priority 1: spot resume checkpoint (most recent, from interrupted run)
ckpt_model = os.path.join(SM_CKPT, MODEL_FILE)
if os.path.exists(ckpt_model):
    print(f"  SPOT RESUME: Restoring checkpoint {MODEL_FILE}")
    shutil.copy2(ckpt_model, os.path.join(CODE_DIR, MODEL_FILE))
    ckpt_ewc = os.path.join(SM_CKPT, EWC_FILE)
    if os.path.exists(ckpt_ewc):
        shutil.copy2(ckpt_ewc, os.path.join(CODE_DIR, EWC_FILE))

# Priority 2: uploaded brain weights (from your local machine via launcher)
elif os.path.isdir(SM_WEIGHTS):
    for f in os.listdir(SM_WEIGHTS):
        src = os.path.join(SM_WEIGHTS, f)
        dst = os.path.join(CODE_DIR, f)
        shutil.copy2(src, dst)
        sz = os.path.getsize(dst) / 1e6
        print(f"  Warm-start: loaded {f} ({sz:.1f} MB)")
else:
    print("  No pre-trained weights found — training from scratch.")

# ── 3. Run RL training ─────────────────────────────────────────────────────
# The RL agent learns by interacting with the simulation — no dataset!
print("\n[3/4] Starting RL training (agent learns from simulation)...")
print("  The satellite agent will explore the environment and improve over time.")
print()

from rl_training.mappo_train import main as train_main
train_main()

# ── 4. Save trained weights to S3 ─────────────────────────────────────────
print("\n[4/4] Saving trained model to S3...")

output_files = (
    glob.glob(os.path.join(CODE_DIR, "ppo_swarm_brain*"))
    + glob.glob(os.path.join(CODE_DIR, "ewc_fisher_swarm.pkl"))
    + glob.glob(os.path.join(CODE_DIR, "episodic_memory*.pkl"))
    + glob.glob(os.path.join(CODE_DIR, "outputs/*.csv"))
)

for f in output_files:
    name = os.path.basename(f)
    # -> S3 (SageMaker uploads SM_MODEL to s3://bucket/output/ automatically)
    shutil.copy2(f, os.path.join(SM_MODEL, name))
    # -> checkpoint (survives spot interruption for resume)
    shutil.copy2(f, os.path.join(SM_CKPT, name))
    sz = os.path.getsize(f) / 1e6
    print(f"  Saved: {name} ({sz:.1f} MB)")

print("\nRL Training complete!")
