"""
scripts/export_episode.py
--------------------------
Runs the trained PPO model for one full episode across all satellites and
exports rich state data for MATLAB visualization.

Outputs:
    outputs/episode_data.csv   - Per-step, per-satellite state (3D ECEF, health, faults)
    outputs/reward_history.csv - Already generated by train.py (200 cycles)
    outputs/gs_positions.csv   - Static ground station ECEF positions

Usage:
    python scripts/export_episode.py
    python scripts/export_episode.py --orbit gps_meo --steps 720
"""

import os
import sys
import argparse
import csv
import numpy as np

# Allow running from project root or from scripts/
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from stable_baselines3 import PPO
from simulation.sat_config import PRESETS
from simulation.satellite_env import MultiSatelliteEnv
from simulation.orbital_physics import (
    anomaly_to_ecef, latlon_to_ecef, GROUND_STATIONS, EARTH_RADIUS_KM
)
from rl_training.ctde_policy import CTDEPolicy
from rl_training.memory import EpisodicMemory

MODEL_PATH = "ppo_swarm_brain.zip"

def main():
    parser = argparse.ArgumentParser(description="Export episode data for MATLAB visualization")
    parser.add_argument("--orbit",  default="starlink_leo")
    parser.add_argument("--steps",  type=int, default=360)
    parser.add_argument("--phase",  type=int, default=6, help="Curriculum phase to evaluate on (1-6)")
    args = parser.parse_args()

    config = PRESETS[args.orbit]
    n      = config.num_satellites

    # ── Load model ────────────────────────────────────────────────────────────
    print(f"Loading trained model from {MODEL_PATH}...")
    try:
        import warnings
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = PPO.load(MODEL_PATH, custom_objects={"policy_class": CTDEPolicy})
    except Exception as e:
        print(f"ERROR: Could not load model: {e}")
        sys.exit(1)

    memory = EpisodicMemory()
    ctx    = memory.get_context()

    # ── Run episode ───────────────────────────────────────────────────────────
    env = MultiSatelliteEnv(config=config, max_steps=args.steps)
    env.curriculum_phase = args.phase
    obs_raw, _ = env.reset()

    print(f"Running {args.steps}-step episode with {n} satellites (Phase {args.phase})...")

    rows = []
    for step in range(args.steps):
        # Build actions for all satellites
        actions = []
        for i in range(n):
            local = np.concatenate([obs_raw[i]["local"], ctx]).astype(np.float32)
            obs_d = {"local": local, "global": obs_raw[i]["global"]}
            a, _  = model.predict(obs_d, deterministic=True)
            actions.append(a)

        obs_raw, rewards, term, trunc, _ = env.step(np.array(actions))

        # Compute ECEF 3D positions for each satellite
        for i in range(n):
            wp = env._walker_params[i]
            ecef = anomaly_to_ecef(
                env.agent_pos[i],
                config.orbit.altitude_km,
                wp["inclination_deg"],
                wp["raan_deg"],
                env.earth_rot_deg
            )
            # Normalised health score: 0 (critical) → 1 (nominal)
            health = 1.0
            if env.in_safe_mode[i]: health = 0.1
            elif env.fault_wheel[i] or env.fault_thruster[i] or env.fault_sensor[i]: health = 0.5
            elif env.agent_battery[i] < 30 or env.agent_fuel[i] < 20: health = 0.7

            rows.append({
                "step":             step + 1,
                "sat_id":           i,
                "plane_id":         wp["plane_id"],
                # Orbital state
                "true_anomaly_deg": round(float(env.agent_pos[i]), 4),
                "altitude_km":      config.orbit.altitude_km,
                # 3D ECEF position (km)
                "ecef_x_km":        round(float(ecef[0]), 4),
                "ecef_y_km":        round(float(ecef[1]), 4),
                "ecef_z_km":        round(float(ecef[2]), 4),
                # Subsystem health
                "battery_pct":      round(float(env.agent_battery[i]), 2),
                "fuel_pct":         round(float(env.agent_fuel[i]), 2),
                "temp_c":           round(float(env.agent_temp[i]), 2),
                # Attitude
                "roll_deg":         round(float(env.agent_attitude[i][0]), 3),
                "pitch_deg":        round(float(env.agent_attitude[i][1]), 3),
                "yaw_deg":          round(float(env.agent_attitude[i][2]), 3),
                # Fault & mode flags  (1 = active)
                "fault_wheel":      int(env.fault_wheel[i]),
                "fault_thruster":   int(env.fault_thruster[i]),
                "fault_sensor":     int(env.fault_sensor[i]),
                "in_safe_mode":     int(env.in_safe_mode[i]),
                "in_recovery":      int(env.in_recovery[i]),
                "eclipse":          int(env.eclipse_mode[i]),
                "gs_los":           int(env.gs_los[i]),
                # AI action taken
                "action_thrust":    round(float(actions[i][0]), 4),
                "action_roll_tq":   round(float(actions[i][1]), 4),
                "action_pitch_tq":  round(float(actions[i][2]), 4),
                "action_yaw_tq":    round(float(actions[i][3]), 4),
                # Reward
                "reward":           round(float(rewards[i]), 4),
                # Aggregated health score for MATLAB colour coding
                "health_score":     health,
            })

        if term or trunc:
            break

    # ── Export episode data ───────────────────────────────────────────────────
    os.makedirs("outputs", exist_ok=True)
    episode_path = "outputs/episode_data.csv"
    fieldnames = list(rows[0].keys())
    with open(episode_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"  ✓ Episode data  → {episode_path}  ({len(rows)} rows)")

    # ── Export static ground station positions ────────────────────────────────
    gs_path = "outputs/gs_positions.csv"
    with open(gs_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["name", "lat_deg", "lon_deg", "ecef_x_km", "ecef_y_km", "ecef_z_km"])
        for gs in GROUND_STATIONS:
            ecef = latlon_to_ecef(gs["lat"], gs["lon"])
            writer.writerow([
                gs["name"], gs["lat"], gs["lon"],
                round(float(ecef[0]), 4),
                round(float(ecef[1]), 4),
                round(float(ecef[2]), 4),
            ])
    print(f"  ✓ Ground stations → {gs_path}  ({len(GROUND_STATIONS)} stations)")
    print(f"\nEarth radius: {EARTH_RADIUS_KM} km  |  Orbital altitude: {config.orbit.altitude_km} km")
    print("Done! Upload both CSVs to MATLAB Online along with visualize_constellation.m")


if __name__ == "__main__":
    main()
